config/routes.rb
Rails.application.routes.draw do
  resources :tiltwers
  devise_for :users
  root 'pages#index'
  resources :parties
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/party.rb
class Party < ApplicationRecord
end

app/models/tiltwer.rb
class Tiltwer < ApplicationRecord
  belongs_to :user

    validates :user, presence: true
    validates :content, presence: true, length: { maximum:  140}

    has_attached_file :photo

    do_not_validate_attachment_file_type :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :tiltwers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery prepend: true

before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :authenticate_user!

  # GET /parties
  # GET /parties.json
  def index
    @parties = Party.all
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
  end

  # GET /parties/new
  def new
    @party = Party.new
  end

  # GET /parties/1/edit
  def edit
  end

  # POST /parties
  # POST /parties.json
  def create
    @party = Party.new(party_params)

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render :show, status: :created, location: @party }
      else
        format.html { render :new }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parties/1
  # PATCH/PUT /parties/1.json
  def update
    respond_to do |format|
      if @party.update(party_params)
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { render :show, status: :ok, location: @party }
      else
        format.html { render :edit }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party.destroy
    respond_to do |format|
      format.html { redirect_to parties_url, notice: 'Party was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_party
      @party = Party.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def party_params
      params.require(:party).permit(:name, :begin, :end, :hours)
    end
end

app/controllers/tiltwers_controller.rb
class TiltwersController < ApplicationController
  before_action :authenticate_user!

  # GET /tiltwers
  # GET /tiltwers.json
  def index
    @tiltwers = Tiltwer.all
  end

  # GET /tiltwers/1
  # GET /tiltwers/1.json
  def show
    @tiltwer = Tiltwer.find(params[:id])
  end

  # GET /tiltwers/new
  def new
    @tiltwer = current_user.tiltwers.new
  end

  # GET /tiltwers/1/edit
  def edit
    @tiltwer = current_user.tiltwers.find(params[:id])
  end

  # POST /tiltwers
  # POST /tiltwers.json
  def create
    @tiltwer = current_user.tiltwers.new(tiltwer_params)

    respond_to do |format|
      if @tiltwer.save
        format.html { redirect_to @tiltwer, notice: 'Tiltwer was successfully created.' }
        format.json { render :show, status: :created, location: @tiltwer }
      else
        format.html { render :new }
        format.json { render json: @tiltwer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tiltwers/1
  # PATCH/PUT /tiltwers/1.json
  def update
    @tiltwer = current_user.tiltwers.find(params[:id])
    respond_to do |format|
      if @tiltwer.update(tiltwer_params)
        format.html { redirect_to @tiltwer, notice: 'Tiltwer was successfully updated.' }
        format.json { render :show, status: :ok, location: @tiltwer }
      else
        format.html { render :edit }
        format.json { render json: @tiltwer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tiltwers/1
  # DELETE /tiltwers/1.json
  def destroy
    @tiltwer.destroy
    respond_to do |format|
      format.html { redirect_to tiltwers_url, notice: 'Tiltwer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tiltwer
      @tiltwer = Tiltwer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tiltwer_params
      params.require(:tiltwer).permit(:user_id, :content, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/tiltwers_helper.rb
module TiltwersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CLASSGEEK</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-custom">
    <div class="container">
      <%= link_to "Classgeek", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
        <%= link_to "teams", parties_path, class: "nav-item nav-link" %>
        <%= link_to "Tiltwer", tiltwers_path, class: "nav-item nav-link" %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
        <% if !user_signed_in? %>
            <%= link_to "sign in", new_user_session_path, class: "nav-item nav-link btn btn-danger mr-2" %>
            <%= link_to "sign up", new_user_registration_path, class: "nav-item nav-link btn btn-primary" %>
        <% else %>
            <%= link_to "logout", destroy_user_session_path, :method => :delete, class: "nav-item  nav-link btn btn-danger" %>
        <% end %>
      </div>
    </div>
   </div>
    </nav>

    <%flash.each do |name, message| %>
        <div class="container">
            <%= content_tag(:div, message, class: "alert alert-info") %>
        </div>
    <% end %>

<div class="container">
    <%= yield %>
</div>
</body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron mt-5">
  <h1 class="display-4">Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>

app/views/parties/_form.html.erb
<%= form_with(model: party, local: true) do |form| %>
  <% if party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(party.errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
        <% party.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :begin, 'inicio' %>
    <%= form.datetime_select :begin %>
  </div>

  <div class="field">
    <%= form.label :end, 'fim' %>
    <%= form.datetime_select :end %>
  </div>

  <div class="field">
    <%= form.label :hours, 'horas' %>
    <%= form.text_field :hours %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parties/edit.html.erb
<h1>Editing Party</h1>

<%= render 'form', party: @party %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Begin</th>
      <th>End</th>
      <th>Hours</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parties.each do |party| %>
      <tr>
        <td><%= party.name %></td>
        <td><%= party.begin %></td>
        <td><%= party.end %></td>
        <td><%= party.hours %></td>
        <td><%= link_to 'Show', party %></td>
        <td><%= link_to 'Edit', edit_party_path(party) %></td>
        <td><%= link_to 'Destroy', party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Party', new_party_path %>

app/views/parties/new.html.erb
<h1>New Party</h1>

<%= render 'form', party: @party %>

<%= link_to 'Back', parties_path %>

app/views/parties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @party.name %>
</p>

<p>
  <strong>Begin:</strong>
  <%= @party.begin %>
</p>

<p>
  <strong>End:</strong>
  <%= @party.end %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @party.hours %>
</p>

<%= link_to 'Edit', edit_party_path(@party) %> |
<%= link_to 'Back', parties_path %>

app/views/tiltwers/_form.html.erb
<%= form_with(model: tiltwer, local: true) do |form| %>
  <% if tiltwer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tiltwer.errors.count, "error") %> prohibited this tiltwer from being saved:</h2>

      <ul>
        <% tiltwer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

   <div class="field">
    <%= form.label :photo, "Imagem" %>
    <%= form.file_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tiltwers/edit.html.erb
<h1>Editing Tiltwer</h1>

<%= render 'form', tiltwer: @tiltwer %>

<%= link_to 'Show', @tiltwer %> |
<%= link_to 'Back', tiltwers_path %>

app/views/tiltwers/index.html.erb
<div class="row mt-5">
    <div class="col-4">
        <div class="card" style="width: 18rem;">
            <% url = Gravatar.new(current_user.email).image_url %>
            <%= image_tag url, class: "card-img-top" %>
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    </div>
    <div class="col-8">

        <p id="notice"><%= notice %></p>

        <h1>Tiltwers</h1>
        <%= link_to 'new Tiltwer', new_tiltwer_path, class: "btn btn-info btn-lg btn-block" %>

        <% @tiltwers.order(id: :desc).each do |tiltwer| %>
        <div class="container">

            <div class="card mt-3">

                    <h5 class="card-header ">
                        <div class="row ml-1">
                            <% perfil = Gravatar.new(tiltwer.user.email).image_url %>
                            <%= image_tag perfil, class: "tiltwers-perfil-img" %>
                            <%= tiltwer.user.username %>
                        </div>
                    </h5>
                <div class="card-body mr-3 ">
                    <p class="card-text"><%= tiltwer.content %></p>
                    <% if tiltwer.photo.file? %>
                        <p class="card-text"><%= image_tag tiltwer.photo.url %></p>
                    <% end %>
                    <%= link_to 'Show', tiltwer, class: "btn btn-primary mr-3 " %>
                <% if tiltwer.user == current_user %>
                <%= link_to 'Edit', edit_tiltwer_path(tiltwer), class: "btn btn-info mr-3 " %>
                    <%= link_to 'Destroy', tiltwer, method: :delete, data: { confirm: 'Are you sure?' }, class:  "btn btn-danger" %>
                    <% end %>
            </div>



    </div>

</div>



    <% end %>


<br>

app/views/tiltwers/new.html.erb
<h1>New Tiltwer</h1>

<%= render 'form', tiltwer: @tiltwer %>

<%= link_to 'Back', tiltwers_path %>

app/views/tiltwers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @tiltwer.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @tiltwer.content %>
</p>

<%= link_to 'Edit', edit_tiltwer_path(@tiltwer) %> |
<%= link_to 'Back', tiltwers_path %>